(() => {
  'use strict';
  let state=JSON.parse(JSON.stringify(window.ALWATEEN_DATA));
  let handle=null,dirty=false;
  const el=id=>document.getElementById(id);
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=value=>String(value).normalize('NFKD').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/ى/g,'ي').trim().toLowerCase();
  const price=value=>value.trim().replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[—-]/g,'–').replace(/\s/g,'');
  function validPrice(value){if(!/^\d+(\.\d{1,2})?(–\d+(\.\d{1,2})?)?$/.test(value))return false;const numbers=value.split('–').map(Number);return numbers.every(Number.isFinite)&&(numbers.length===1||numbers[1]>=numbers[0]);}
  function changed(){dirty=true;el('save-status').textContent='توجد تعديلات لم تُحفظ. اضغط «حفظ ملف البيانات» عند الانتهاء.';}
  function category(){return state.services.find(item=>item.id===el('edit-category').value);}
  function renderRows(){const current=category();const query=normalize(el('edit-search').value);const rows=current.rows.filter(row=>normalize(row.name).includes(query));el('service-count').textContent=`${rows.length} خدمة — ${current.rows.filter(row=>row.enabled===false).length} معطّلة في هذا القسم`;
    el('edit-rows').innerHTML=rows.map(row=>`<div class="editor-row ${row.enabled===false?'disabled':''}"><div class="editor-service-name">${escape(row.name)}<small>${row.enabled===false?'معطّلة — لا تظهر للعملاء':'مفعّلة — تظهر للعملاء'}</small></div><label>السعر بالريال<input data-price="${escape(row.id)}" value="${escape(row.price)}" dir="ltr" inputmode="decimal" aria-label="سعر ${escape(row.name)}"></label><button type="button" class="btn btn--line" data-toggle="${escape(row.id)}">${row.enabled===false?'تفعيل':'تعطيل'}</button><button type="button" class="btn btn--line danger" data-delete="${escape(row.id)}">حذف</button></div>`).join('');
  }
  function renderAll(){for(const id of ['edit-category','add-category'])el(id).replaceChildren(...state.services.map(item=>new Option(item.title,item.id)));for(const field of ['name','phone','iban','email','address','unifiedNumber'])el('office-form').elements[field].value=state.office[field]||'';renderRows();}
  el('edit-category').addEventListener('change',()=>{el('edit-search').value='';renderRows();});el('edit-search').addEventListener('input',renderRows);
  el('edit-rows').addEventListener('change',event=>{const input=event.target;if(!input.matches('[data-price]'))return;const value=price(input.value);if(!validPrice(value)){input.setCustomValidity('أدخل مبلغًا صحيحًا أو نطاقًا مثل 50–100.');input.reportValidity();return;}input.setCustomValidity('');category().rows.find(row=>row.id===input.dataset.price).price=value;input.value=value;changed();});
  el('edit-rows').addEventListener('input',event=>{if(event.target.matches('input'))event.target.setCustomValidity('');});
  el('edit-rows').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const id=button.dataset.toggle||button.dataset.delete;const index=category().rows.findIndex(row=>row.id===id);if(index<0)return;const row=category().rows[index];if(button.dataset.delete){if(!confirm(`حذف خدمة «${row.name}» من قائمة الخدمات؟`))return;category().rows.splice(index,1);}else row.enabled=row.enabled===false;changed();renderRows();});
  el('add-service').addEventListener('submit',event=>{event.preventDefault();const name=el('add-name').value.trim(),value=price(el('add-price').value);if(!name){el('add-name').setCustomValidity('اكتب اسم الخدمة.');el('add-name').reportValidity();return;}if(!validPrice(value)){el('add-price').setCustomValidity('أدخل مبلغًا مثل 75 أو نطاقًا مثل 50–100.');el('add-price').reportValidity();return;}const target=state.services.find(item=>item.id===el('add-category').value);if(target.rows.some(row=>normalize(row.name)===normalize(name))){el('add-name').setCustomValidity('الخدمة موجودة بالفعل في هذا القسم.');el('add-name').reportValidity();return;}target.rows.push({id:'custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,9),name,price:value,enabled:true});el('edit-category').value=target.id;el('edit-search').value='';renderRows();changed();el('add-status').textContent='أُضيفت الخدمة. احفظ ملف البيانات لتثبيت الإضافة.';el('add-name').value='';el('add-price').value='';});
  el('add-service').addEventListener('input',event=>event.target.setCustomValidity(''));
  el('office-form').addEventListener('input',event=>event.target.setCustomValidity(''));
  el('office-form').addEventListener('submit',event=>{event.preventDefault();const form=event.target;let phone=form.elements.phone.value.replace(/[\s()-]/g,'');if(/^05\d{8}$/.test(phone))phone='+966'+phone.slice(1);if(/^9665\d{8}$/.test(phone))phone='+'+phone;if(phone&&!/^\+9665\d{8}$/.test(phone)){form.elements.phone.setCustomValidity('أدخل جوالًا سعوديًا صحيحًا.');form.elements.phone.reportValidity();return;}const iban=form.elements.iban.value.replace(/\s/g,'').toUpperCase();if(iban){const digits=(iban.slice(4)+iban.slice(0,4)).replace(/[A-Z]/g,c=>String(c.charCodeAt(0)-55));let remainder=0;for(const digit of digits)remainder=(remainder*10+Number(digit))%97;if(!/^SA\d{22}$/.test(iban)||remainder!==1){form.elements.iban.setCustomValidity('أدخل آيبانًا سعوديًا صحيحًا أو اتركه فارغًا.');form.elements.iban.reportValidity();return;}}state.office={...state.office,name:form.elements.name.value.trim(),phone,iban,email:form.elements.email.value.trim(),address:form.elements.address.value.trim(),addressShort:form.elements.address.value.trim(),unifiedNumber:form.elements.unifiedNumber.value.trim()};changed();el('office-status').textContent='تم اعتماد البيانات. احفظ ملف البيانات عند الانتهاء.';});
  function parseData(text){const match=text.trim().match(/^window\.ALWATEEN_DATA\s*=\s*([\s\S]*);\s*$/);if(!match)throw Error('اختر ملف site-data.js الصحيح.');const data=JSON.parse(match[1]);if(!Array.isArray(data.services)||!data.services.length||!data.office)throw Error('ملف البيانات غير صالح.');const ids=new Set();for(const c of data.services){if(typeof c.id!=='string'||typeof c.title!=='string'||!Array.isArray(c.rows))throw Error('قسم غير صالح.');for(const row of c.rows){if(typeof row.id!=='string'||typeof row.name!=='string'||!row.name.trim()||!validPrice(row.price)||ids.has(row.id)||(row.enabled!==undefined&&typeof row.enabled!=='boolean'))throw Error('خدمة غير صالحة.');ids.add(row.id);}}for(const key of ['name','phone','email','address'])if(typeof data.office[key]!=='string')throw Error('بيانات المكتب غير صالحة.');return data;}
  el('connect-folder').addEventListener('click',async()=>{if(!window.showDirectoryPicker){el('save-status').textContent='المتصفح لا يدعم الحفظ المباشر. زر حفظ ملف البيانات سينزّل site-data.js لاستبداله داخل مجلد data.';return;}if(dirty&&!confirm('سيتم تحميل البيانات من المجلد المختار واستبدال التعديلات غير المحفوظة. متابعة؟'))return;try{const folder=await window.showDirectoryPicker({mode:'readwrite'});await folder.getFileHandle('index.html');const dataFolder=await folder.getDirectoryHandle('data');const selected=await dataFolder.getFileHandle('site-data.js');const parsed=parseData(await(await selected.getFile()).text());state=parsed;handle=selected;dirty=false;renderAll();el('file-label').textContent=`الحفظ المباشر: ${folder.name}/data/site-data.js`;el('save-status').textContent='تم ربط المجلد. التعديلات ستُكتب فيه عند الضغط على حفظ.';}catch(error){if(error.name!=='AbortError')el('save-status').textContent='تعذر فتح بيانات المجلد: '+error.message;}});
  el('import-data').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(dirty&&!confirm('استبدال التعديلات الحالية ببيانات الملف؟'))return;try{state=parseData(await file.text());handle=null;dirty=false;renderAll();el('file-label').textContent='ملف مستورد: '+file.name;el('save-status').textContent='تم تحميل الملف. اختر مجلد المشروع للحفظ المباشر أو نزّل الملف بعد التعديل.';}catch(error){el('save-status').textContent=error.message;}event.target.value='';});
  el('save-data').addEventListener('click',async()=>{const invalid=[...el('edit-rows').querySelectorAll('input')].find(input=>!validPrice(price(input.value)));if(invalid){invalid.setCustomValidity('صحّح السعر قبل الحفظ.');invalid.reportValidity();return;}const content='window.ALWATEEN_DATA = '+JSON.stringify(state,null,2)+';\n';try{if(handle){const writable=await handle.createWritable();await writable.write(content);await writable.close();dirty=false;el('save-status').textContent='حُفظت البيانات داخل المشروع. حدّث معاينة الموقع ثم ارفع الملفات المحدّثة.';}else{const url=URL.createObjectURL(new Blob([content],{type:'text/javascript;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='site-data.js';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dirty=false;el('save-status').textContent='نُزّل site-data.js. استبدل به الملف الموجود داخل مجلد data ثم ارفع الموقع.';}}catch(error){el('save-status').textContent='تعذر الحفظ: '+error.message;}});
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  renderAll();
})();
